name: My first workflow

on: push

jobs: 
   first_job:
      runs-on: ubuntu-latest
      steps: 
      - name: welcome message
        run: echo "Hello"
      - name: download repo
        uses: actions/checkout@v4

      - name: list files
        run: ls
      - name: read file
        run: cat README.md